[package]
name = "rusty-doc"
version = "0.1.0"
edition = "2024"

[dependencies]
kurosabi = { version = "0.6.13", features = ["tokio-server", "json", "file"] }
tokio = { version = "1.49.0", features = ["full"] }
comrak = { version = "0.49", default-features = true }
pulldown-latex = "0.7"
env_logger = "0.11.8"
log = "0.4"
tf-idf-vectorizer = "0.10.1"
dashmap = "6.1.0"
